### PR TITLE
Database agnosticism (REGEXP)

### LINKED ISSUE #1: Database agnosticism (REGEXP)
After installing the extension when I try to create a page with <EventCalendar> tag (as the example) I get this error:

"A database query error has occurred. This may indicate a bug in the software.

Notice: Uncommitted DB writes (transaction from DatabaseBase::query (DatabaseBase::query)). in /home/hscps/hsc.tia.mat.br/w/includes/db/Database.php on line 3944"

My config:
MediaWiki 1.22.0
PHP     5.3.27 (cgi-fcgi)
SQLite 3.7.7.1

### PR DESCRIPTION
**Pull request by rennerocha**
Fixes #1

I didn' t find a way to use the PDO method sqliteCreateFunction (http://www.php.net/manual/en/pdo.sqlitecreatefunction.php) to define REGEXP in SQLite. To be able to do that, I need to have access to the protected property _mConn_ of _DatabaseSqlite_ class.

The solution I found is to retrieve all page titles and check with PHP function preg_match if the title is from an event. It will be slower than a direct search in database, but I can't find a better way.

For working in PostgreSQL I just set the right regex operator based on _DatabaseBase_ subclass.

### CODE REVIEW

**Comment by malexmave** [comment]
Tried the patch out on my install, worked just fine. I did not notice any performance impact, but my wiki is very small, so I don't know how it would react to very large SQLite DBs.

Thanks for the patch!

**Comment by serpent213** [comment]
Looks good. Just a few comments...
1. The namespace filter would work with SQLite, wouldn't it? So line 143 should be outside the if-clause.
2. We should avoid duplication of the regex pattern, i.e. let's define `$titlePattern = '^[0-9]{4}/[0-9]{2}/[0-9]{2}_.'` and use that where necessary. Using "." instead of [:alnum:] should do no harm.
3. Might make sense to use the "S" modifier for preg_match, see http://php.net/manual/en/reference.pcre.pattern.modifiers.php.

I don't think there's a performance penalty in this implementation. The way I suggested would make SQLite call preg_match anyway, so the overhead might even be lower now.

**Comment by serpent213** [comment]
I think the original regex would work as well.

``` php
improper@moonraker:/tmp% cat preg.php 
<?php
$s = '2014/02/14_foo';
if ( preg_match( '@^[0-9]{4}/[0-9]{2}/[0-9]{2}_[[:alnum:]]@S', $s )) {
  echo( "match\n" );
} else {
  echo( "no match\n" );
}
?>
improper@moonraker:/tmp% php < preg.php
match
improper@moonraker:/tmp% php -v
PHP 5.4.17 (cli) (built: Sep 12 2013 23:14:23) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
```

BTW, the coding style is some kind of pseudo-MediaWiki – but don't worry too much, I would fix that afterwards.

**Comment by rennerocha** [comment]
If the original regex works well, I see no problem using that. I will change here to follow your second suggestion.

**Comment by serpent213** [comment]
Great, thanks!

**Pull request merged**
